services:
  app:
    container_name: go-product-api
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=admin:Password1!@tcp(mysql:3306)/ProductApi?charset=utf8mb4&parseTime=True&loc=Local
      - JWT_KEY=jwt_secret_key
    depends_on:
      mysql:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - go-network

  mysql:
    container_name: go-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password1!
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Password1!
      - MYSQL_DATABASE=ProductApi
    ports:
      - '33066:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - go-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  cache:
    image: redis
    restart: always
    ports:
      - '63799:6379'
    networks:
      - go-network

volumes:
  dbdata:

networks:
  go-network:
    driver: bridge