@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhbGljZSIsImVtYWlsIjoiYWxpY2VAd29yay5jb20iLCJleHAiOjE3NDI0MDAxMjUsImp0aSI6IjAxOTVhOWZkLTllYmEtNzdkYi05NGQyLWQ0MTM5NGNhNDUxYSJ9.PgSwRm0W3B5nrKvoBOxuFFX1oYGa9L8mp5tgcMubl1o

### Login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "alice",
  "password": "Password123"
}

### Logout
POST {{host}}/api/v1/auth/logout
Authorization: Bearer {{token}}


### Users
### Get a user by id
GET {{host}}/api/v1/users/1
Authorization: Bearer {{token}}

### Get all users
GET {{host}}/api/v1/users?page=1&page_size=1
Authorization: Bearer {{token}}

### Create a new user
POST {{host}}/api/v1/auth/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "alice",
  "password": "Password123"
}

### Update a user
PUT {{host}}/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "alice",
  "password": "Password123",
  "email": "alice@work.com"
}

### Delete a user
DELETE {{host}}/api/v1/users/2
Authorization: Bearer {{token}}


### Categories

### Get all categories
GET {{host}}/api/v1/categories
Authorization: Bearer {{token}}

### Get a category by id
GET {{host}}/api/v1/categories/1
Authorization: Bearer {{token}}

### Create a new category
POST {{host}}/api/v1/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 1",
  "description": "Category 1 description"
}

### Update a category
PUT {{host}}/api/v1/categories/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 1",
  "description": "Category 1 description updated"
}

### Delete a category
DELETE {{host}}/api/v1/categories/1
Authorization: Bearer {{token}}

### Products

### Get all products
GET {{host}}/api/v1/products
Authorization: Bearer {{token}}

### Get all products by category
GET {{host}}/api/v1/products?category_id=3
Authorization: Bearer {{token}}

### Get a product by id
GET {{host}}/api/v1/products/1
Authorization: Bearer {{token}}

### Create a new product
POST {{host}}/api/v1/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": 100.00,
  "category_id": 3
}

### Update a product
PUT {{host}}/api/v1/products/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Product 1",
  "description": "Product 1 description updated",
  "price": 101.00,
  "category_id": 3
}

### Delete a product
DELETE {{host}}/api/v1/products/1
Authorization: Bearer {{token}}